name: Hello World
on: push
jobs:
  say_hello:
    name: Say Hello World
    runs-on: ubuntu-18.04
    steps:
      - name: echo
        run: |
          echo 'Hello'
          echo 'World'
      - name: connect
        run: |
          echo "Connect to server with password ${{ secrets.MY_PASSWORD }}"
  build:
    name: Build System Project
    runs-on: ubuntu-18.04
    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Composer install
       uses: php-actions/composer@v6

     - name: PHPStan
       uses: php-actions/phpstan@v3

  test_output:
    runs-on: ubuntu-18.04
    steps:
      - name: step1
        id: step_1
        run: |
          echo ::set-output name=VERSION::v1.0
      - name: step2
        run: |
           echo "La version ${{ steps.step_1.outputs.VERSION }} est déployée"